services:
  app:
    build: .
    command: rake watch
    image: ucblib/beekeeper:development
    environment:
      - BEEKEEPER_WATCHERS
      - RSPEC_DOCKER
      - SLACK_API_TOKEN
    secrets:
      - source: .env
        target: /opt/app/.env
    privileged: true
    volumes:
      - ./:/opt/app
      - /var/run/docker.sock:/var/run/docker.sock

secrets:
  .env:
    file: .env
