version: "3.5"

services:
  app:
    build: .
    command: watch
    environment:
      SLACK_WEBHOOK_URL: "${SLACK_WEBHOOK_URL}"
    volumes:
      - ./:/opt/app
      - /var/run/docker.sock:/var/run/docker.sock
